version: '3.8'

services:
  job-portal-web:
    image: nginx:alpine
    container_name: job-portal-app-assignment
    ports:
      - "8081:80"
    volumes:
      - ./web-app:/usr/share/nginx/html
    networks:
      - assignment-network

  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub-assignment
    ports:
      - "4444:4444"
    networks:
      - assignment-network

  chrome-node:
    image: selenium/node-chrome:4.15.0
    container_name: chrome-node-assignment
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
    networks:
      - assignment-network
    shm_size: 2gb

networks:
  assignment-network:
    driver: bridge
